#pragma kernel CSMain

struct vertex
{
    float3 position;
    float3 normal;
    float4 tangent;
};

RWTexture2D<float4> result;
StructuredBuffer<vertex> gpuVertices;
int frameWidth;
float2 startPixel;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int x = id.x % frameWidth + startPixel.x;
    int y = id.x / frameWidth + startPixel.y;
    result[float2(x, y)] = float4(gpuVertices[id.x].position, 1);
}
